worker_processes auto;
pid /tmp/output-runtime/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    access_log /tmp/output-runtime/log/access.log;
    error_log  /tmp/output-runtime/log/error.log;

    client_body_temp_path /tmp/output-runtime/nginx-temp/client-body;
    proxy_temp_path /tmp/output-runtime/nginx-temp/proxy;
    fastcgi_temp_path /tmp/output-runtime/nginx-temp/fastcgi;
    uwsgi_temp_path /tmp/output-runtime/nginx-temp/uwsgi;
    scgi_temp_path /tmp/output-runtime/nginx-temp/scgi;

    server {
        listen 1080 default_server;
        listen [::]:1080 default_server;
        server_name Output;

        # Angular app
        root /tmp/output-runtime/www;
        index index.html;

        __BASE_HREF_REDIRECT__

        # Frontend-Routes (Angular Router) -> immer index.html
        location __BASE_HREF__ {
            alias /tmp/output-runtime/www/;
            try_files $uri $uri/ __BASE_HREF__index.html;
        }

        # Backend-API
        location __BASE_HREF__api/ {
            proxy_pass http://127.0.0.1:3000/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
